[package]
name = "rust-socks5"
version = "0.1.0"
authors = ["conblem <mail@conblem.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
trust-dns-resolver = { version = "0.19.3", features = ["dns-over-rustls", "dnssec-ring"] }
